# Generated by Django 6.0.3 on 2026-04-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_rol', 'Cambio de rol'), ('toggle_permiso', 'Toggle de permiso'), ('toggle_activo', 'Activar/desactivar usuario'), ('solicitud_creada', 'Solicitud de rol creada'), ('solicitud_aprobada', 'Solicitud de rol aprobada'), ('solicitud_rechazada', 'Solicitud de rol rechazada'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Evento de bitácora',
                'verbose_name_plural': 'Eventos de bitácora',
                'ordering': ['-fecha'],
            },
        ),
    ]
