# Generated by Django 5.2.12 on 2026-04-10 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_rol', 'Cambio de rol'), ('toggle_permiso', 'Toggle de permiso'), ('toggle_activo', 'Activar/desactivar usuario'), ('solicitud_creada', 'Solicitud de rol creada'), ('solicitud_aprobada', 'Solicitud de rol aprobada'), ('solicitud_rechazada', 'Solicitud de rol rechazada'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de bitácora',
                'verbose_name_plural': 'Eventos de bitácora',
                'ordering': ['-fecha'],
            },
        ),
    ]
