# Generated by Django 5.2.12 on 2026-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraevento',
            name='hash_registro',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
