# Generated by Django 5.2.12 on 2026-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraevento',
            name='tipo',
            field=models.CharField(choices=[('cambio_rol', 'Cambio de rol'), ('toggle_permiso', 'Toggle de permiso'), ('toggle_activo', 'Activar/desactivar usuario'), ('solicitud_creada', 'Solicitud de rol creada'), ('solicitud_aprobada', 'Solicitud de rol aprobada'), ('solicitud_rechazada', 'Solicitud de rol rechazada'), ('login', 'Inicio de sesion'), ('logout', 'Cierre de sesion'), ('verificacion_expediente', 'Verificacion / edicion de expediente'), ('eliminar_expediente', 'Eliminacion de expediente'), ('acceso_migrante', 'Acceso de migrante al portal'), ('acceso_migrante_fallido', 'Intento fallido de acceso al portal'), ('solicitud_arco_creada', 'Solicitud ARCO creada'), ('solicitud_arco_aprobada', 'Solicitud ARCO aprobada por Operativo'), ('solicitud_arco_firmada', 'Solicitud ARCO firmada por Coordinador'), ('solicitud_arco_rechazada', 'Solicitud ARCO rechazada'), ('solicitud_arco_ejecutada', 'Solicitud ARCO ejecutada'), ('solicitud_arco_firmada_cancelacion', 'Cancelacion ARCO firmada por Coordinador (pendiente Admin)'), ('solicitud_arco_cancelacion_rechazada', 'Cancelacion ARCO rechazada por Admin en paso final'), ('expediente_cancelado_arco', 'Expediente eliminado por ejecucion ARCO de cancelacion')], max_length=60),
        ),
    ]
