# Generated by Django 4.2.30 on 2026-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_bitacoraevento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraevento',
            name='tipo',
            field=models.CharField(choices=[('cambio_rol', 'Cambio de rol'), ('toggle_permiso', 'Toggle de permiso'), ('toggle_activo', 'Activar/desactivar usuario'), ('solicitud_creada', 'Solicitud de rol creada'), ('solicitud_aprobada', 'Solicitud de rol aprobada'), ('solicitud_rechazada', 'Solicitud de rol rechazada'), ('login', 'Inicio de sesion'), ('logout', 'Cierre de sesion'), ('verificacion_expediente', 'Verificacion / edicion de expediente'), ('eliminar_expediente', 'Eliminacion de expediente'), ('acceso_migrante', 'Acceso de migrante al portal'), ('acceso_migrante_fallido', 'Intento fallido de acceso al portal'), ('solicitud_arco_creada', 'Solicitud ARCO creada'), ('solicitud_arco_aprobada', 'Solicitud ARCO aprobada por Operativo'), ('solicitud_arco_firmada', 'Solicitud ARCO firmada por Coordinador'), ('solicitud_arco_rechazada', 'Solicitud ARCO rechazada'), ('solicitud_arco_ejecutada', 'Solicitud ARCO ejecutada'), ('solicitud_arco_firmada_cancelacion', 'Cancelacion ARCO firmada por Coordinador (pendiente Admin)'), ('solicitud_arco_cancelacion_rechazada', 'Cancelacion ARCO rechazada por Admin en paso final'), ('expediente_cancelado_arco', 'Expediente eliminado por ejecucion ARCO de cancelacion'), ('aviso_privacidad_aceptado', 'Aceptacion de Aviso de Privacidad de Casa Monarca')], max_length=60),
        ),
    ]
