# Generated by Django 6.0.3 on 2026-05-22 19:12

import django.db.models.deletion
import portal_migrante.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0003_expediente_folio_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rectificacion', 'Rectificacion'), ('cancelacion', 'Cancelacion'), ('oposicion', 'Oposicion')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revision'), ('aprobada_operativo', 'Aprobada por Operativo — esperando firma'), ('rechazada', 'Rechazada'), ('firmada_coordinador', 'Firmada por Coordinador — pendiente de ejecucion'), ('ejecutada', 'Ejecutada')], default='pendiente', max_length=25)),
                ('descripcion_cifrada', portal_migrante.models.EncryptedTextFieldArco(help_text='Descripcion libre del cambio solicitado por el migrante.')),
                ('campos_solicitados', portal_migrante.models.EncryptedTextFieldArco(blank=True, help_text='JSON con campo:valor_nuevo para solicitudes de rectificacion.')),
                ('hash_solicitud', models.CharField(max_length=64)),
                ('folio_hash_verificacion', models.CharField(max_length=64)),
                ('respuesta_operativo', models.TextField(blank=True)),
                ('fecha_respuesta_operativo', models.DateTimeField(blank=True, null=True)),
                ('respuesta_coordinador', models.TextField(blank=True)),
                ('fecha_firma_coordinador', models.DateTimeField(blank=True, null=True)),
                ('firma_digital', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_firmadas', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_arco', to='expediente.expediente')),
                ('operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
