# Generated by Django 5.2.12 on 2026-05-22 23:23

import django.db.models.deletion
import portal_migrante.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_migrante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarco',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_ejecutadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudarco',
            name='cambios_propuestos',
            field=portal_migrante.models.EncryptedTextFieldArco(blank=True, default='', help_text='JSON de cambios concretos propuestos por el Operativo (rectificacion).'),
        ),
        migrations.AddField(
            model_name='solicitudarco',
            name='etiqueta_oposicion',
            field=portal_migrante.models.EncryptedTextFieldArco(blank=True, default='', help_text='Etiqueta de restriccion escrita por el Operativo (oposicion).'),
        ),
        migrations.AddField(
            model_name='solicitudarco',
            name='fecha_ejecucion_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudarco',
            name='firma_digital_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudarco',
            name='respuesta_admin',
            field=models.TextField(blank=True),
        ),
    ]
