# Generated by Django 5.2.12 on 2026-05-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_expediente_etiquetas_oposicion'),
        ('portal_migrante', '0002_solicitudarco_admin_solicitudarco_cambios_propuestos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarco',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco', to='expediente.expediente'),
        ),
    ]
