# Generated by Django 6.0.3 on 2026-04-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(help_text='Creador o Nombre del Rol Destinatario', max_length=50)),
                ('llave_aes_cifrada', models.TextField()),
            ],
            options={
                'verbose_name': 'Acceso a expediente',
                'verbose_name_plural': 'Accesos a expediente',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateField()),
                ('datos_cifrados', models.TextField()),
                ('nonce', models.TextField()),
                ('tag', models.TextField()),
                ('verificado', models.BooleanField(default=False)),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('hash_expediente', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
