# Generated by Django 5.2.12 on 2026-04-05 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateField()),
                ('datos_cifrados', models.TextField()),
                ('nonce', models.TextField()),
                ('tag', models.TextField()),
                ('llave_aes_cifrada', models.TextField()),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('hash_expediente', models.CharField(max_length=64)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
