# Generated by Django 6.0.3 on 2026-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='folio_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
