# Generated by Django 5.2.12 on 2026-05-22 23:23

import expediente.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_expediente_folio_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='etiquetas_oposicion',
            field=expediente.models.EncryptedTextFieldExpediente(blank=True, default=''),
        ),
    ]
