# Generated by Django 6.0.3 on 2026-04-23 22:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, unique=True)),
                ('llave_publica', models.TextField()),
            ],
            options={
                'verbose_name': 'Llave de rol',
                'verbose_name_plural': 'Llaves de rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador_Administracion', 'Coordinador de Administración'), ('Coordinador_Legal', 'Coordinador Legal'), ('Coordinador_Psicosocial', 'Coordinador Psicosocial'), ('Coordinador_Humanitario', 'Coordinador Humanitario'), ('Coordinador_Comunicacion', 'Coordinador de Comunicación'), ('Operativo', 'Operativo'), ('Usuario', 'Usuario')], default='Usuario', max_length=50)),
                ('telefono', usuarios.models.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('llave_publica', models.TextField(blank=True, null=True)),
                ('llave_privada', usuarios.models.EncryptedTextField(blank=True, null=True)),
                ('certificado_digital', models.TextField(blank=True, null=True)),
                ('fecha_expiracion_certificado', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_actual', models.CharField(max_length=50)),
                ('rol_solicitado', models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador_Administracion', 'Coordinador de Administración'), ('Coordinador_Legal', 'Coordinador Legal'), ('Coordinador_Psicosocial', 'Coordinador Psicosocial'), ('Coordinador_Humanitario', 'Coordinador Humanitario'), ('Coordinador_Comunicacion', 'Coordinador de Comunicación'), ('Operativo', 'Operativo'), ('Usuario', 'Usuario')], max_length=50)),
                ('mensaje', models.TextField(blank=True, help_text='Explica por qué necesitas este cambio de rol')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de rol',
                'verbose_name_plural': 'Solicitudes de rol',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='AccesoLlaveRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave_privada_rol_cifrada', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_rol', to=settings.AUTH_USER_MODEL)),
                ('llave_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='usuarios.llaverol')),
            ],
            options={
                'verbose_name': 'Acceso a llave de rol',
                'verbose_name_plural': 'Accesos a llave de rol',
                'unique_together': {('llave_rol', 'usuario')},
            },
        ),
    ]
