# Generated by Django 5.2.12 on 2026-04-10 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_llave_privada_usuario_llave_publica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_actual', models.CharField(max_length=20)),
                ('rol_solicitado', models.CharField(choices=[('Admin', 'Administrador'), ('Voluntario', 'Voluntario'), ('Junior', 'Junior'), ('Auditor', 'Auditor')], max_length=20)),
                ('mensaje', models.TextField(blank=True, help_text='Explica por qué necesitas este cambio de rol')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de rol',
                'verbose_name_plural': 'Solicitudes de rol',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
