# Generated by Django 5.2.12 on 2026-04-15 21:27

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='certificado_digital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_expiracion_certificado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='llave_privada',
            field=usuarios.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=usuarios.models.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
    ]
